<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RollForward>Major</RollForward>
		<UserSecretsId>520ce071-63a5-44e5-9c21-2169b7e52f1d</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="../ProjectMemoryProxy.Persistence/ProjectMemoryProxy.Persistence.csproj" />
	  <ProjectReference Include="..\ProjectMemoryProxy.BasicMemory\ProjectMemoryProxy.BasicMemory.csproj" />
	</ItemGroup>

</Project>
