version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # default location of `.github/workflows`
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:37"
      timezone: "Europe/Berlin"
  
  - package-ecosystem: "nuget"
    directory: "/source"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:27"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:17"
      timezone: "Europe/Berlin"
