// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMemoryProxy.Persistence;

#nullable disable

namespace ProjectMemoryProxy.Persistence.Migrations
{
    [DbContext(typeof(ProjectMemoryProxyDbContext))]
    [Migration("20261003083030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ProjectRoutingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemoryProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemoryProjectId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ProjectRoutings");
                });

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ProjectRoutingEntity", b =>
                {
                    b.OwnsMany("ProjectMemoryProxy.Persistence.Entities.ContextBindingEntity", "Bindings", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BindingName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("BindingType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("RoutingProjectId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long>("UpdatedAt")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("RoutingProjectId");

                            b1.HasIndex("BindingType", "BindingName")
                                .IsUnique();

                            b1.ToTable("ContextBindings");

                            b1.WithOwner()
                                .HasForeignKey("RoutingProjectId");
                        });

                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
