// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMemoryProxy.Persistence;

#nullable disable

namespace ProjectMemoryProxy.Persistence.Migrations
{
    [DbContext(typeof(ProjectMemoryProxyDbContext))]
    partial class ProjectMemoryProxyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ContextBindingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BindingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BindingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoutingProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoutingProjectId");

                    b.HasIndex("BindingType", "BindingName")
                        .IsUnique();

                    b.ToTable("ContextBindings");
                });

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ProjectRoutingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemoryProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemoryProjectId")
                        .IsUnique();

                    b.HasIndex("MemoryProjectName")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ProjectRoutings");
                });

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ContextBindingEntity", b =>
                {
                    b.HasOne("ProjectMemoryProxy.Persistence.Entities.ProjectRoutingEntity", "RoutingProject")
                        .WithMany("Bindings")
                        .HasForeignKey("RoutingProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutingProject");
                });

            modelBuilder.Entity("ProjectMemoryProxy.Persistence.Entities.ProjectRoutingEntity", b =>
                {
                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
