<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\source\ProjectMemoryProxy.BasicMemory\ProjectMemoryProxy.BasicMemory.csproj" />
	</ItemGroup>

</Project>
